name: gradle
on:
  push:
    branches:
      - master # run the action on your projects default branch

jobs:
  build:
    name: gradle
    runs-on: ubuntu-latest
    permissions: # The Dependency Submission API requires write permission
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: Root Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          use-gradlew: false
          gradle-build-module: |-
            :
          gradle-build-configuration: |-
            compileClasspath
